
CREATE OR REPLACE FUNCTION DIGITOS(CARACTER NUMBER) RETURN NUMBER as

LONGITUD NUMBER;
ERROR_e EXCEPTION;
VARIABLE1  NUMBER;
CONTADOR1 NUMBER : =10;
TOTAL1 NUMBER := 10;
ACUMULADOR NUMBER;

BEGIN
  
SELECT LENGTH(CARACTER) INTO LONGITUD FROM DUAL; 

IF LONGITUD = 10 THEN


    FOR i IN 1..LENGTH(LONGITUD) LOOP
    
         VARIABLE1 := substr(CARACTER,i,1);
         TOTAL1 := TOTAL1 + ( VARIABLE1 * CONTADOR1);
         CONTADOR1 := CONTADOR1 - 1;
         
        END LOOP;
        
    RETURN TOTAL1;

ELSE 

    RAISE ERROR_e;
  
END IF;

EXCEPTION

  WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20992,'Numero de carecteres incorrecto');
 
  
END;
